### ISSUE TITLE
Misinterprets Non-Craftable with simple item varient.

### ISSUE THREAD

**Issue by Hexenum** [TryHardDo/EasyCopyPaste#1] opened 2023-08-09 12:11 UTC
![image](https://github.com/TryHardDo/EasyCopyPaste/assets/94901586/55381fce-358d-4739-8c3a-553c27cb9b06)

**Comment by TryHardDo** [comment] 2023-08-09 12:13
Also offers all possible items while asking for simple ks items. Example: Killstreak Scattergun you will receive the list if you have it in stock with strange, profks and the rest combinations.

**Comment by TryHardDo** [comment] 2023-09-09 08:58
Duplicate of #2

**Closed as completed by TryHardDo** 2023-09-09 08:58 UTC
Labels: bug, duplicate
